### PR TITLE
umbraco 13 and .net 8 support

### PR DESCRIPTION
**Pull request by garpunkal**
Added support for umbraco 13.

### CODE REVIEW

**Comment by craigs100** [comment]
Any idea when this will get merged? Can't upgrade a V10.x site to V13.1.1 without it :(

**Comment by Yinzy00** [comment]
Hey @callumbwhyte, we are also waiting on this for upgrading multiple projectes. Any idea when this will get merged 😄?

**Comment by craigs100** [comment]
Would donuts make a difference?

**Comment by greypvine** [comment]
> Would donuts make a difference?

What about a pint? Two pints?

**Comment by YaMoef** [comment]
> > Would donuts make a difference?
> 
> What about a pint? Two pints?

We should opt for the big guns, what about a crate of beer?

**Comment by craigs100** [comment]
Please?

**Comment by callumbwhyte** [comment]
Hey everybody!

Firstly, sorry for the extreme delay here. Life has been a little crazy lately...

Thanks for your PR @garpunkal! I have now pushed [v3.2.0](https://github.com/callumbwhyte/umbraco-search-extensions/releases/tag/release-3.2.0) that includes v13 support + v14 support – available from all good package marketplaces.

I'll now be calling in all of your bids – I believe that's donuts from @craigs100, a pint + 2 pints from @greyopteryx, and a crate of beer from @YaMoef... Keep the offers rolling if anyone wants new features 🤪 _(I joke, of course!)_

Thanks for using the package, happy searching!

Callum

**Pull request closed without merging**
